Repository TOMToolkit/tom_base, pull requests merged in 2023-01, with the labels that each got.

#572 Share Photometry
  docs/managing_data/customizing_data_sharing.rst
  docs/managing_data/index.rst
  tom_alerts/migrations/0005_alertstreammessage.py
  tom_alerts/migrations/0006_alter_alertstreammessage_exchange_status.py
  tom_alerts/models.py
  tom_base/settings.py
  tom_dataproducts/alertstreams/__init__.py
  tom_dataproducts/alertstreams/hermes.py
  tom_dataproducts/forms.py
  tom_dataproducts/migrations/0011_reduceddatum_message.py
  tom_dataproducts/models.py
  tom_dataproducts/templates/tom_dataproducts/dataproduct_list.html
  tom_dataproducts/templates/tom_dataproducts/partials/dataproduct_list_for_target.html
  tom_dataproducts/templates/tom_dataproducts/partials/photometry_datalist_for_target.html
  tom_dataproducts/templates/tom_dataproducts/partials/photometry_for_target.html
  tom_dataproducts/templates/tom_dataproducts/partials/recent_photometry.html
  tom_dataproducts/templates/tom_dataproducts/partials/share_target_data.html
  tom_dataproducts/templatetags/dataproduct_extras.py
  tom_dataproducts/urls.py
  tom_dataproducts/views.py
  tom_targets/serializers.py
  tom_targets/templates/tom_targets/target_detail.html
Labels: enhancement

#590 incomplete first draft of expanded data sharing docs
  docs/managing_data/customizing_data_sharing.rst
  docs/managing_data/index.rst
  docs/managing_data/stream_pub_sub.rst
  docs/managing_data/tom_direct_sharing.rst
Labels: documentation

#597 update TNS harvester with new TNS API protocol
  tom_catalogs/harvesters/tns.py
Labels: bug

#593 Apply more robust name recognition during target and data ingestion
  tom_dataproducts/alertstreams/hermes.py
  tom_observations/templates/tom_observations/observation_form.html
  tom_targets/models.py
  tom_targets/tests/tests.py
  tom_targets/views.py
Labels: bug
