Repository TOMToolkit/tom_base, pull requests merged in 2023-10, with the labels that each got.

#695 Clarify sidereal vs non-sidereal setup prompt
  tom_setup/management/commands/tom_setup.py
Labels: enhancement, documentation

#694 Fix Issues with DataProduct Deletion in DeleteView
  tom_dataproducts/views.py
Labels: bug

#692 remove reliance on alerce page return
  tom_alerts/brokers/alerce.py
Labels: bug, alert brokers

#693 remove grating for FLOYDS observations.
  tom_observations/facilities/lco.py
Labels: bug

#726 Fix a bug with initiating LCO template forms
  tom_dataproducts/sharing.py
  tom_observations/facilities/lco.py
Labels: bug

#717 fix "critical" codacy issues
  manage.py
  tom_alerts/alerts.py
  tom_alerts/brokers/alerce.py
  tom_alerts/brokers/antares.py
  tom_alerts/brokers/fink.py
  tom_alerts/brokers/hermes.py
  tom_alerts/brokers/scout.py
  tom_alerts/tests/brokers/test_lasair.py
  tom_alerts/views.py
  tom_common/exceptions.py
  tom_dataproducts/forced_photometry/forced_photometry_service.py
  tom_dataproducts/migrations/0010_manual_20210305_fix_spectroscopy.py
  tom_dataproducts/processors/photometry_processor.py
  tom_dataproducts/processors/spectroscopy_processor.py
  tom_dataproducts/views.py
  tom_observations/facilities/lco.py
  tom_observations/facilities/ocs.py
  tom_observations/facility.py
  tom_observations/tests/facilities/test_ocs.py
  tom_observations/tests/tests.py
  tom_observations/views.py
Labels: Patch Party

#718 Feature/install poetry
  .github/workflows/github-release.yml
  .github/workflows/pypi-release.yml
  .github/workflows/run-canary-tests.yml
  .github/workflows/run-tests.yml
  poetry.lock
  pyproject.toml
  tom_base/__init__.py
  tom_common/templates/tom_common/index.html
  tom_common/urls.py
Labels: Patch Party
