Repository TOMToolkit/tom_base, pull requests merged in 2023-12, with the labels that each got.

#763 only show unknown status warning if there are any
  tom_targets/templates/tom_targets/partials/target_unknown_statuses.html
Labels: bug

#789 Enhancement: Extend settings to set default plotly theme.
  tom_common/apps.py
  tom_setup/templates/tom_setup/settings.tmpl
Labels: toolkit customization

#794 Added developer and contributor pages plus how to acknowledge the too…
  README.md
  docs/index.rst
  docs/introduction/about.rst
  docs/introduction/acknowledging_tom_toolkit.rst
  docs/introduction/credits.rst
Labels: documentation
