Repository TOMToolkit/tom_base, pull requests merged in 2024-10, with the labels that each got.

#1052 add cancel button on observation record detail page.
  tom_observations/templates/tom_observations/observationrecord_detail.html
Labels: User

#1071 add function to retrieve facility form classes for display
  tom_observations/api_views.py
  tom_observations/facility.py
  tom_observations/views.py
Labels: high priority

#1085 Set user in facility before calling the get_form_classes_for_display.
  tom_observations/views.py
Labels: User

#1063 767 new tom creation documentation
  docs/api/tom_observations/models.rst
  docs/api/tom_targets/groups.rst
  docs/introduction/manual_installation.rst
  docs/observing/index.rst
  docs/targets/index.rst
  docs/targets/target_fields.rst
  tom_observations/facilities/lco.py
  tom_observations/templates/tom_observations/observation_form.html
  tom_observations/views.py
Labels: documentation
